Rails.application.routes.draw do
  root 'pages#index'
  get '/about' => 'pages#about'
  get '/events' => 'events#index'
  get '/contact' => 'contacts#index'
  get '/teams' => 'teams#index'
  post '/teams' => 'teams#create'
  get '/users/new' => 'users#new'
  get '/mobile-login' => 'sessions#mobile'
  post '/users' => 'users#create'
  post '/sessions' => 'sessions#create'
  delete '/sessions' => 'sessions#destroy'
  get '/admins/dashboard' => 'admins#index'
  get '/mentors' => 'mentors#new'
  get '/password/recovery' => 'users#recover_password'
  get '/password/recovery/confirmed' => 'users#recover_password_email_sent'
  post '/password/recovery' => 'users#request_password_recovery_token'
  get '/password/reset/confirmation' => 'users#password_reset_confirmation'

  post '/password/reset/:token' => 'users#reset_password'
  get '/password/reset/:token' => 'users#edit_password'
  post '/teams/roster/:id' => 'users#add_team'
  delete '/teams/roster/:id' => 'users#remove_team'
  delete '/teams/:id/destroy' => 'teams#destroy'
  delete '/users/:id/destroy' => 'users#destroy'
  delete '/wait_list/:id/destroy' => 'users#remove_from_wait_list'
end
